var b;b||=typeof Module != 'undefined' ? Module : {};var aa=globalThis.document?.currentScript?.src,t="",u;try{t=(new URL(".",aa)).href}catch{}u=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var w=console.log.bind(console),x=console.error.bind(console),y,z=!1,A,B,D,E,F,G,H,I;
function J(){var a=K.buffer;A=new Int8Array(a);D=new Int16Array(a);B=new Uint8Array(a);new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);G=new Float32Array(a);H=new Float64Array(a);I=new BigInt64Array(a);new BigUint64Array(a)}function L(a){b.onAbort?.(a);a="Aborted("+a+")";x(a);z=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var M;
async function ba(a){if(!y)try{var d=await u(a);return new Uint8Array(d)}catch{}if(a==M&&y)a=new Uint8Array(y);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,d){try{var c=await ba(a);return await WebAssembly.instantiate(c,d)}catch(e){x(`failed to asynchronously prepare wasm: ${e}`),L(e)}}
async function da(a){var d=M;if(!y)try{var c=fetch(d,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){x(`wasm streaming compile failed: ${e}`),x("falling back to ArrayBuffer instantiation")}return ca(d,a)}class ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=a=>{for(;0<a.length;)a.shift()(b)},O=[],P=[],fa=()=>{var a=b.preRun.shift();P.push(a)},Q=0,R=null,S=!0,ha=[null,[],[]],T=globalThis.TextDecoder&&new TextDecoder,U=(a,d=0)=>{var c=d;for(var e=c+void 0;a[c]&&!(c>=e);)++c;if(16<c-d&&a.buffer&&T)return T.decode(a.subarray(d,c));for(e="";d<c;){var g=a[d++];if(g&128){var n=a[d++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|n);else{var q=a[d++]&63;g=224==(g&240)?(g&15)<<12|n<<6|q:(g&7)<<18|n<<12|q<<6|a[d++]&63;65536>g?e+=String.fromCharCode(g):
(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e};b.noExitRuntime&&(S=b.noExitRuntime);b.print&&(w=b.print);b.printErr&&(x=b.printErr);b.wasmBinary&&(y=b.wasmBinary);if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();
b.ccall=(a,d,c,e)=>{var g={string:h=>{var l=0;if(null!==h&&void 0!==h&&0!==h){for(var f=l=0;f<h.length;++f){var k=h.charCodeAt(f);127>=k?l++:2047>=k?l+=2:55296<=k&&57343>=k?(l+=4,++f):l+=3}var r=l+1;f=l=V(r);k=B;if(0<r){r=f+r-1;for(var C=0;C<h.length;++C){var m=h.codePointAt(C);if(127>=m){if(f>=r)break;k[f++]=m}else if(2047>=m){if(f+1>=r)break;k[f++]=192|m>>6;k[f++]=128|m&63}else if(65535>=m){if(f+2>=r)break;k[f++]=224|m>>12;k[f++]=128|m>>6&63;k[f++]=128|m&63}else{if(f+3>=r)break;k[f++]=240|m>>18;
k[f++]=128|m>>12&63;k[f++]=128|m>>6&63;k[f++]=128|m&63;C++}}k[f]=0}}return l},array:h=>{var l=V(h.length);A.set(h,l);return l}};a=b["_"+a];var n=[],q=0;if(e)for(var p=0;p<e.length;p++){var v=g[c[p]];v?(0===q&&(q=W()),n[p]=v(e[p])):n[p]=e[p]}c=a(...n);return c=function(h){0!==q&&X(q);return"string"===d?h?U(B,h):"":"boolean"===d?!!h:h}(c)};
b.getValue=function(a,d="i8"){d.endsWith("*")&&(d="*");switch(d){case "i1":return A[a];case "i8":return A[a];case "i16":return D[a>>1];case "i32":return E[a>>2];case "i64":return I[a>>3];case "float":return G[a>>2];case "double":return H[a>>3];case "*":return F[a>>2];default:L(`invalid type for getValue: ${d}`)}};
var X,V,W,K,ia={e:()=>L(""),b:a=>{var d=B.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var e=d*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(536870912,65536*Math.ceil(Math.max(a,e)/65536))-K.buffer.byteLength+65535)/65536|0;try{K.grow(e);J();var g=1;break a}catch(n){}g=void 0}if(g)return!0}return!1},f:a=>{S||(b.onExit?.(a),z=!0);throw new ea(a);},d:()=>52,c:function(){return 70},a:(a,d,c,e)=>{for(var g=0,n=0;n<c;n++){var q=F[d>>2],p=F[d+4>>2];d+=8;for(var v=0;v<p;v++){var h=a,
l=B[q+v],f=ha[h];0===l||10===l?((1===h?w:x)(U(f)),f.length=0):f.push(l)}g+=p}F[e>>2]=g;return 0}};
function Y(){function a(){b.calledRun=!0;if(!z){Z.h();b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var d=b.postRun.shift();O.push(d)}N(O)}}if(0<Q)R=Y;else{if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)fa();N(P);0<Q?R=Y:b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()}}var Z;
(async function(){function a(c){c=Z=c.exports;b._compress_image_jpegli=c.i;b._malloc=c.j;b._free=c.k;b._free_result_data_jpegli=c.l;X=c.m;V=c.n;W=c.o;K=b.wasmMemory=c.g;J();Q--;b.monitorRunDependencies?.(Q);0==Q&&R&&(c=R,R=null,c());return Z}Q++;b.monitorRunDependencies?.(Q);var d={a:ia};if(b.instantiateWasm)return new Promise(c=>{b.instantiateWasm(d,(e,g)=>{c(a(e,g))})});M??=b.locateFile?b.locateFile("encoder.wasm",t):t+"encoder.wasm";return a((await da(d)).instance)})();Y();
