var d;d||=typeof Module != 'undefined' ? Module : {};var n="./this.program",aa=globalThis.document?.currentScript?.src,p="",q;try{p=(new URL(".",aa)).href}catch{}q=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var u=console.log.bind(console),v=console.error.bind(console),w,x=!1,y,z,A,B,C,D,E,F,G;
function H(){var a=I.buffer;z=new Int8Array(a);B=new Int16Array(a);A=new Uint8Array(a);new Uint16Array(a);C=new Int32Array(a);D=new Uint32Array(a);E=new Float32Array(a);F=new Float64Array(a);G=new BigInt64Array(a);new BigUint64Array(a)}function J(a){d.onAbort?.(a);a="Aborted("+a+")";v(a);x=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var K;
async function ba(a){if(!w)try{var b=await q(a);return new Uint8Array(b)}catch{}if(a==K&&w)a=new Uint8Array(w);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(e){v(`failed to asynchronously prepare wasm: ${e}`),J(e)}}
async function da(a){var b=K;if(!w)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){v(`wasm streaming compile failed: ${e}`),v("falling back to ArrayBuffer instantiation")}return ca(b,a)}class L{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var M=a=>{for(;0<a.length;)a.shift()(d)},N=[],O=[],ea=()=>{var a=d.preRun.shift();O.push(a)},P=0,Q=null,R=!0,S=0,T={},fa=a=>{if(!(a instanceof L||"unwind"==a))throw a;},U=a=>{y=a;R||0<S||(d.onExit?.(a),x=!0);throw new L(a);},ha=a=>{if(!x)try{a()}catch(b){fa(b)}finally{if(!(R||0<S))try{y=a=y,U(a)}catch(b){fa(b)}}},V={},ia=()=>{if(!W){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:n||"./this.program"},
b;for(b in V)void 0===V[b]?delete a[b]:a[b]=V[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);W=c}return W},W,ja=(a,b,c)=>{var e=A;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;e[b++]=g}else if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6;e[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12;e[b++]=128|g>>6&63;e[b++]=128|g&63}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63;e[b++]=128|g>>6&63;e[b++]=128|g&63;h++}}e[b]=
0;return b-f},ka=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},la=[null,[],[]],ma=globalThis.TextDecoder&&new TextDecoder,na=(a,b=0)=>{var c=b;for(var e=c+void 0;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&ma)return ma.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|
a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e};d.noExitRuntime&&(R=d.noExitRuntime);d.print&&(u=d.print);d.printErr&&(v=d.printErr);d.wasmBinary&&(w=d.wasmBinary);d.thisProgram&&(n=d.thisProgram);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();
d.ccall=(a,b,c,e)=>{var f={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=ka(k)+1;var r=X(l);ja(k,r,l);l=r}return l},array:k=>{var l=X(k.length);z.set(k,l);return l}};a=d["_"+a];var h=[],g=0;if(e)for(var m=0;m<e.length;m++){var t=f[c[m]];t?(0===g&&(g=oa()),h[m]=t(e[m])):h[m]=e[m]}c=a(...h);return c=function(k){0!==g&&pa(g);return"string"===b?k?na(A,k):"":"boolean"===b?!!k:k}(c)};
d.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return z[a];case "i8":return z[a];case "i16":return B[a>>1];case "i32":return C[a>>2];case "i64":return G[a>>3];case "float":return E[a>>2];case "double":return F[a>>3];case "*":return D[a>>2];default:J(`invalid type for getValue: ${b}`)}};
var qa,pa,X,oa,I,ra={b:()=>J(""),a:()=>{R=!1;S=0},c:(a,b)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!b)return 0;var c=setTimeout(()=>{delete T[a];ha(()=>qa(a,performance.now()))},b);T[a]={id:c,u:b};return 0},d:a=>{var b=A.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(536870912,65536*Math.ceil(Math.max(a,e)/65536))-I.buffer.byteLength+65535)/65536|0;try{I.grow(e);H();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},
g:(a,b)=>{var c=0,e=0,f;for(f of ia()){var h=b+c;D[a+e>>2]=h;c+=ja(f,h,Infinity)+1;e+=4}return 0},i:(a,b)=>{var c=ia();D[a>>2]=c.length;a=0;for(var e of c)a+=ka(e)+1;D[b>>2]=a;return 0},j:a=>{y=a;U(a)},f:()=>52,e:(a,b,c,e)=>{for(var f=0,h=0;h<c;h++){var g=D[b>>2],m=D[b+4>>2];b+=8;for(var t=0;t<m;t++){var k=a,l=A[g+t],r=la[k];0===l||10===l?((1===k?u:v)(na(r)),r.length=0):r.push(l)}f+=m}D[e>>2]=f;return 0},h:U};
function Y(){function a(){d.calledRun=!0;if(!x){Z.l();d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();N.push(b)}M(N)}}if(0<P)Q=Y;else{if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ea();M(O);0<P?Q=Y:d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()}}var Z;
(async function(){function a(c){c=Z=c.exports;d._compress_image=c.m;d._malloc=c.n;d._free=c.o;d._free_result_data=c.p;qa=c.q;pa=c.r;X=c.s;oa=c.t;I=d.wasmMemory=c.k;H();P--;d.monitorRunDependencies?.(P);0==P&&Q&&(c=Q,Q=null,c());return Z}P++;d.monitorRunDependencies?.(P);var b={a:ra};if(d.instantiateWasm)return new Promise(c=>{d.instantiateWasm(b,(e,f)=>{c(a(e,f))})});K??=d.locateFile?d.locateFile("encoder.wasm",p):p+"encoder.wasm";return a((await da(b)).instance)})();Y();
