var d;d||=typeof Module != 'undefined' ? Module : {};var n="./this.program",aa=globalThis.document?.currentScript?.src,p="",q;try{p=(new URL(".",aa)).href}catch{}q=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var u=console.log.bind(console),v=console.error.bind(console),w,x=!1,y,z,A,B,C,D,E,F;
function G(){var a=H.buffer;y=new Int8Array(a);A=new Int16Array(a);z=new Uint8Array(a);new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);D=new Float32Array(a);E=new Float64Array(a);F=new BigInt64Array(a);new BigUint64Array(a)}function I(a){d.onAbort?.(a);a="Aborted("+a+")";v(a);x=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var J;
async function ba(a){if(!w)try{var b=await q(a);return new Uint8Array(b)}catch{}if(a==J&&w)a=new Uint8Array(w);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(e){v(`failed to asynchronously prepare wasm: ${e}`),I(e)}}
async function da(a){var b=J;if(!w)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){v(`wasm streaming compile failed: ${e}`),v("falling back to ArrayBuffer instantiation")}return ca(b,a)}class ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var K=a=>{for(;0<a.length;)a.shift()(d)},L=[],M=[],fa=()=>{var a=d.preRun.shift();M.push(a)},N=0,O=null,P=!0,Q={},S=()=>{if(!R){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:n||"./this.program"},b;for(b in Q)void 0===Q[b]?delete a[b]:a[b]=Q[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);R=c}return R},R,T=(a,b,c)=>{var e=z;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);
if(127>=g){if(b>=c)break;e[b++]=g}else if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6;e[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12;e[b++]=128|g>>6&63;e[b++]=128|g&63}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63;e[b++]=128|g>>6&63;e[b++]=128|g&63;h++}}e[b]=0;return b-f},U=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},ha=[null,[],[]],V=globalThis.TextDecoder&&new TextDecoder,W=(a,b=0)=>{var c=
b;for(var e=c+void 0;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&V)return V.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e};d.noExitRuntime&&(P=d.noExitRuntime);d.print&&(u=d.print);d.printErr&&(v=d.printErr);
d.wasmBinary&&(w=d.wasmBinary);d.thisProgram&&(n=d.thisProgram);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();
d.ccall=(a,b,c,e)=>{var f={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=U(k)+1;var r=X(l);T(k,r,l);l=r}return l},array:k=>{var l=X(k.length);y.set(k,l);return l}};a=d["_"+a];var h=[],g=0;if(e)for(var m=0;m<e.length;m++){var t=f[c[m]];t?(0===g&&(g=ia()),h[m]=t(e[m])):h[m]=e[m]}c=a(...h);return c=function(k){0!==g&&ja(g);return"string"===b?k?W(z,k):"":"boolean"===b?!!k:k}(c)};
d.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a];case "i8":return y[a];case "i16":return A[a>>1];case "i32":return B[a>>2];case "i64":return F[a>>3];case "float":return D[a>>2];case "double":return E[a>>3];case "*":return C[a>>2];default:I(`invalid type for getValue: ${b}`)}};
var ja,X,ia,H,ka={b:a=>{var b=z.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(536870912,65536*Math.ceil(Math.max(a,e)/65536))-H.buffer.byteLength+65535)/65536|0;try{H.grow(e);G();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},d:(a,b)=>{var c=0,e=0,f;for(f of S()){var h=b+c;C[a+e>>2]=h;c+=T(f,h,Infinity)+1;e+=4}return 0},e:(a,b)=>{var c=S();C[a>>2]=c.length;a=0;for(var e of c)a+=U(e)+1;C[b>>2]=a;return 0},f:a=>{P||
(d.onExit?.(a),x=!0);throw new ea(a);},c:()=>52,a:(a,b,c,e)=>{for(var f=0,h=0;h<c;h++){var g=C[b>>2],m=C[b+4>>2];b+=8;for(var t=0;t<m;t++){var k=a,l=z[g+t],r=ha[k];0===l||10===l?((1===k?u:v)(W(r)),r.length=0):r.push(l)}f+=m}C[e>>2]=f;return 0}};
function Y(){function a(){d.calledRun=!0;if(!x){Z.h();d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();L.push(b)}K(L)}}if(0<N)O=Y;else{if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)fa();K(M);0<N?O=Y:d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()}}var Z;
(async function(){function a(c){c=Z=c.exports;d._compress_image=c.i;d._malloc=c.j;d._free=c.k;d._get_result_data=c.l;d._get_result_size=c.m;ja=c.n;X=c.o;ia=c.p;H=d.wasmMemory=c.g;G();N--;d.monitorRunDependencies?.(N);0==N&&O&&(c=O,O=null,c());return Z}N++;d.monitorRunDependencies?.(N);var b={a:ka};if(d.instantiateWasm)return new Promise(c=>{d.instantiateWasm(b,(e,f)=>{c(a(e,f))})});J??=d.locateFile?d.locateFile("encoder.wasm",p):p+"encoder.wasm";return a((await da(b)).instance)})();Y();
